GET http://localhost:3000/menu
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJzdWIiOjIsImlhdCI6MTYzNjM3NTI0NywiZXhwIjoxNjM2Mzc1MzY3fQ.cVGOXXB9rRLUl0b3FQSIEVP0FM9cRTcDnJQ7yDDH71c 
